name: Compile Image
on:
  release:
    types:
      - created
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/setup-buildx-action@v3.0.0
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest,enable={{ is_default_branch }}
      - uses: docker/build-push-action@v5.1.0
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
