name: Build
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/setup-buildx-action@v3.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5.2.0
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest,enable={{ is_default_branch }}
      - uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: ruff --output-format=github .
  wheel:
    runs-on: ubuntu-22.04
    needs:
      - ruff
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8
      - run: pip install build
      - run: python -m build
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}.Wheel
          path: dist/*
  nuitka:
    runs-on: windows-2022
    needs:
      - ruff
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.8
      - run: pip install -r requirements-dev.txt
      - run: python -m nuitka --standalone --onefile --output-filename="fivedesc.exe" --output-dir="build" --assume-yes-for-downloads fivedesc.py
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}.Windows
          path: build/fivedesc.exe
  release:
    runs-on: ubuntu-22.04
    needs:
      - wheel
      - nuitka
    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ github.event.repository.name }}.Wheel
          path: dist/Python Wheels
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ${{ github.event.repository.name }}.Windows
          path: dist/Windows
      - run: ls -R
      - run: 7z a ${{ github.event.repository.name }}.zip ${{ github.workspace }}
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ github.event.repository.name }}
          path: dist/*
  run:
    runs-on: ubuntu-22.04
    needs:
      - docker
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
