name: Compile Image
on:
  release:
    types:
      - created
  push:
  pull_request:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: docker/setup-buildx-action@v3.0.0
      - uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/metadata-action@v5.2.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=short,prefix=
            type=raw,value=latest,enable={{ is_default_branch }}
      - uses: docker/build-push-action@v5.1.0
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
